[manager]

prepend_keymap = [
	{ on = [ "K" ], run = "arrow -50%", desc = "Move cursor up 5 lines" },
	{ on = [ "J" ], run = "arrow 50%",  desc = "Move cursor down 5 lines" },
	{ on = [ "<C-u>" ], run = "arrow -50%",  desc = "Move cursor down 15 lines" },
	{ on = [ "<C-d>" ], run = "arrow 50%", desc = "Move cursor up 15 lines" },
	{ on = [ "<C-b>" ], run = "arrow -100%",  desc = "Move cursor down 15 lines" },
	{ on = [ "<C-f>" ], run = "arrow 100%", desc = "Move cursor up 15 lines" },
	{ on = [ "<C-a>" ], run = "select_all --state=none",            desc = "Toggle select all files" },
	{ on = [ "T", "1" ], run = "tab_close 0", desc = "close tab 1" },
	{ on = [ "T", "2" ], run = "tab_close 1", desc = "close tab 2" },
	{ on = [ "T", "3" ], run = "tab_close 2", desc = "close tab 3" },
	{ on = [ "T", "4" ], run = "tab_close 3", desc = "close tab 4" },
	{ on = [ "<C-s>" ], run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },
]
