[manager]
ratio         = [ 1, 4, 2 ]
sort_by        = "alphabetical"
sort_sensitive = true
sort_reverse   = false
sort_dir_first = true
show_hidden    = false
show_symlink   = true
linemode       = "size_and_mtime"

[preview]
tab_size        = 2
max_width       = 600
max_height      = 900
image_quality   = 75
sixel_fraction  = 15
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]
cache_dir = "/home/joker/.cache/yazi"
image_filter    = "triangle"

[opener]
edit = [
  { run = '$EDITOR "$@"', block = true },
]
open = [
  { run = 'xdg-open "$@"', desc = "Open" },
]
unzip = [
  { run = 'mcomix "$@"' },
  { run = 'unzip -d "${file%.*}" "$file"', desc = "Extract here" },
  { run = 'unzip -O sjis -d "${file%.*}" "$file"', desc = "Extract here (SJIS)" },
]
unrar = [
  { run = 'mcomix "$@"' },
  { run = 'unrar x "$1" "${1%.*}/', desc = "Extract here" },
]
image = [
  { run = 'swayimg "$@"', orphan = true, desc = "swayimg" },
  { run = 'swayimg --gallery "$@"', orphan = true, desc = "swayimg (gallery)" },
  { run = 'nsxiv "$@"', orphan = true, desc = "nsxiv" },
  { run = 'vimiv "$@"', orphan = true, desc = "vimiv" },
]
media = [
  { run = 'mpv "$@"', orphan = true, desc = "mpv" },
  { run = 'mpv -v "$@"', desc = "mpv (verbose)", block = true },
  { run = 'mpv --profile=headphone "$@"', orphan = true, desc = "mpv (headphone)" },
  { run = 'mpv --profile=surround-hdmi "$@"', orphan = true, desc = "mpv (hdmi)" },
  { run = 'mpv --profile=bt "$@"', orphan = true, desc = "mpv (bt)" },
  { run = 'dmm-renamer "$@"', desc = "dmm-renamer", block = true },
  { run = 'convert_to_mp4 "$@"', desc = "convert_to_mp4", block = true },
]

[open]
rules = [
  { name = "*/", use = ["edit", "open"] },
  { mime = "text/*", use = "edit" },
  { mime = "image/*", use = "image" },
  { mime = "video/*", use = "media" },
  { mime = "audio/*", use = "media" },
  { mime = "inode/x-empty", use = "edit" },

  { mime = "application/json", use = "edit" },
  { mime = "*/javascript", use = "edit" },

  { mime = "application/zip", use = "unzip" },
  { mime = "application/x-rar", use = "unrar" },

  { mime = "*", use = "open" },
]

[tasks]
micro_workers    = 20
macro_workers    = 25
bizarre_retry    = 5
image_alloc      = 536870912  # 512MB
image_bound      = [ 8000, 8000 ]
suppress_preload = false

[plugin]
prepend_previewers = [
  { name = "*.zip", run = "image_archive" },
	{ mime = "application/x-tar",           run = "ouch" },
	{ mime = "application/x-bzip2",         run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar",           run = "ouch" },
	{ mime = "application/x-xz",            run = "ouch" },
  { name = "*.md", run = "glow" },
]

[[plugin.prepend_fetchers]]
id   = "mime"
if   = "!mime"
name = "*"
run  = "mime-ext"
prio = "high"
