[manager]
layout         = [ 1, 4, 2 ]
sort_by        = "natural"
sort_sensitive = true
sort_reverse   = false
sort_dir_first = true
show_hidden    = false
show_symlink   = true

[preview]
cache_dir = "/home/joker/.cache/yazi"

[opener]
folder = [
  { exec = '$EDITOR "$@"', block = true },
]

unzip = [
{ exec = 'mcomix "$@"' },
  { exec = 'unzip -d "${file%.*}" "$file"', desc = "Extract here" },
  { exec = 'unzip -O sjis -d "${file%.*}" "$file"', desc = "Extract here (SJIS)" },
]
unrar = [
{ exec = 'mcomix "$@"' },
  { exec = 'unrar x "$1" "${1%.*}/', desc = "Extract here" },
]
text = [
  { exec = '$EDITOR "$@"', block = true },
]
image = [
  { exec = 'nsxiv "$@"', desc = "Open" },
]
media = [
  { exec = 'mpv "$@"', desc = "mpv" },
  { exec = 'mpv --profile=headphone "$@"', desc = "mpv (headphone)" },
  { exec = 'mpv --profile=surround-hdmi "$@"', desc = "mpv (hdmi)" },
  { exec = 'mpv --profile=bt "$@"', desc = "mpv (bt)" },
  { exec = 'mpv --profile=jack "$@"', desc = "mpv (jack)" },
  { exec = 'dmm-renamer "$@"', desc = "dmm-renamer", block = true },
]
fallback = [
  { exec = 'open "$@"', desc = "Open" },
  { exec = 'open -R "$@"', desc = "Reveal in Finder" },
]

[open]
rules = [
{ name = "*/", use = "folder" },
  { mime = "text/*", use = "text" },
  { mime = "image/*", use = "image" },
  { mime = "video/*", use = "media" },
  { mime = "audio/*", use = "media" },
  { mime = "inode/x-empty", use = "text" },

  { mime = "application/json", use = "text" },
  { mime = "*/javascript", use = "text" },

  { mime = "application/zip", use = "unzip" },
  { mime = "application/x-rar", use = "unrar" },

  { mime = "*", use = "fallback" },
]
