[manager]
ratio         = [ 1, 4, 2 ]
sort_by        = "alphabetical"
sort_sensitive = true
sort_reverse   = false
sort_dir_first = true
show_hidden    = false
show_symlink   = true
linemode       = "size"

[preview]
tab_size        = 2
max_width       = 600
max_height      = 900
image_quality   = 75
sixel_fraction  = 15
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]
cache_dir = "/home/joker/.cache/yazi"
image_filter    = "triangle"

[opener]
edit = [
  { exec = '$EDITOR "$@"', block = true },
]
open = [
  { exec = 'xdg-open "$@"', desc = "Open" },
]
unzip = [
  { exec = 'mcomix "$@"' },
  { exec = 'unzip -d "${file%.*}" "$file"', desc = "Extract here" },
  { exec = 'unzip -O sjis -d "${file%.*}" "$file"', desc = "Extract here (SJIS)" },
]
unrar = [
  { exec = 'mcomix "$@"' },
  { exec = 'unrar x "$1" "${1%.*}/', desc = "Extract here" },
]
image = [
  { exec = 'nsxiv "$@"', orphan = true, desc = "nsxiv" },
  { exec = 'vimiv "$@"', orphan = true, desc = "vimiv" },
]
media = [
  { exec = 'mpv "$@"', orphan = true, desc = "mpv" },
  { exec = 'mpv -v "$@"', desc = "mpv (verbose)", block = true },
  { exec = 'mpv --profile=headphone "$@"', orphan = true, desc = "mpv (headphone)" },
  { exec = 'mpv --profile=surround-hdmi "$@"', orphan = true, desc = "mpv (hdmi)" },
  { exec = 'mpv --profile=bt "$@"', orphan = true, desc = "mpv (bt)" },
  { exec = 'dmm-renamer "$@"', desc = "dmm-renamer", block = true },
]

[open]
rules = [
  { name = "*/", use = ["edit", "open"] },
  { mime = "text/*", use = "edit" },
  { mime = "image/*", use = "image" },
  { mime = "video/*", use = "media" },
  { mime = "audio/*", use = "media" },
  { mime = "inode/x-empty", use = "edit" },

  { mime = "application/json", use = "edit" },
  { mime = "*/javascript", use = "edit" },

  { mime = "application/zip", use = "unzip" },
  { mime = "application/x-rar", use = "unrar" },

  { mime = "*", use = "open" },
]

[tasks]
micro_workers    = 20
macro_workers    = 25
bizarre_retry    = 5
image_alloc      = 536870912  # 512MB
image_bound      = [ 2048, 2048 ]
suppress_preload = false

[plugin]

preloaders = [
	{ name = "*", cond = "!mime", exec = "mime", multi = true, prio = "high" },
	# Image
	{ mime = "image/vnd.djvu", exec = "noop" },
	{ mime = "image/*",        exec = "image" },
	# Video
	{ mime = "video/*", exec = "video" },
	# PDF
	{ mime = "application/pdf", exec = "pdf" },
]
previewers = [
	{ name = "*/", exec = "folder", sync = true },
	# Code
	{ mime = "text/*",                 exec = "code" },
	{ mime = "*/xml",                  exec = "code" },
	{ mime = "*/javascript",           exec = "code" },
	{ mime = "*/x-wine-extension-ini", exec = "code" },
	# JSON
	{ mime = "application/json", exec = "json" },
	# Image
	{ mime = "image/vnd.djvu", exec = "noop" },
	{ mime = "image/*",        exec = "image" },
	# Video
	{ mime = "video/*", exec = "video" },
	# PDF
	{ mime = "application/pdf", exec = "pdf" },
	# Archive
	{ mime = "application/zip",             exec = "archive" },
	{ mime = "application/gzip",            exec = "archive" },
	{ mime = "application/x-tar",           exec = "archive" },
	{ mime = "application/x-bzip",          exec = "archive" },
	{ mime = "application/x-bzip2",         exec = "archive" },
	{ mime = "application/x-7z-compressed", exec = "archive" },
	{ mime = "application/x-rar",           exec = "archive" },
	{ mime = "application/xz",              exec = "archive" },
	# Fallback
	{ name = "*", exec = "file" },
]
