[manager]
layout         = [ 1, 4, 2 ]
sort_by        = "natural"
sort_sensitive = true
sort_reverse   = false
sort_dir_first = true
show_hidden    = false
show_symlink   = true

[preview]
cache_dir = "/home/joker/.cache/yazi"

[opener]
folder = [
	{ exec = '$EDITOR "$@"', block = true },
]

unzip = [
	{ exec = 'unzip -d "${file%.*}" "$file"', display_name = "Extract here" },
	{ exec = 'unzip -O sjis -d "${file%.*}" "$file"', display_name = "Extract here (SJIS)" },
]
unrar = [
	{ exec = 'unrar x "$1" "${1%.*}/', display_name = "Extract here" },
]
text = [
	{ exec = '$EDITOR "$@"', block = true },
]
image = [
	{ exec = 'nsxiv "$@"', display_name = "Open" },
]
media = [
	{ exec = 'mpv "$@"', display_name = "mpv" },
	{ exec = 'mpv --profile=headphone "$@"', display_name = "mpv (headphone)" },
	{ exec = 'mpv --profile=surround-hdmi "$@"', display_name = "mpv (hdmi)" },
	{ exec = 'mpv --profile=bt "$@"', display_name = "mpv (bt)" },
	{ exec = 'mpv --profile=jack "$@"', display_name = "mpv (jack)" },
  { exec = 'dmm-renamer "$@"' }
]
fallback = [
	{ exec = 'open "$@"', display_name = "Open" },
	{ exec = 'open -R "$@"', display_name = "Reveal in Finder" },
]

[open]
rules = [
  { name = "*/", use = "folder" },
	{ mime = "text/*", use = "text" },
	{ mime = "image/*", use = "image" },
	{ mime = "video/*", use = "media" },
	{ mime = "audio/*", use = "media" },
	{ mime = "inode/x-empty", use = "text" },

	{ mime = "application/json", use = "text" },
	{ mime = "*/javascript", use = "text" },

	{ mime = "application/zip", use = "unzip" },
	{ mime = "application/x-rar", use = "unrar" },

	{ mime = "*", use = "fallback" },
]
