# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins.local-zfunc]
local = "~/.zfunc"
apply = ["fpath"]

[plugins.local-completion]
local = "~/.zsh/completion"
apply = ["fpath"]

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
apply = ["defer"]

[plugins.fast-syntax-highlighting]
github = 'zdharma-continuum/fast-syntax-highlighting'
apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"

[plugins.asdf]
github = "asdf-vm/asdf"

[plugins.dotfiles-main]
local = "~/dotfiles/zsh/conf.d"
use = ["main.zsh"]

[plugins.dotfiles-defers]
local = "~/dotfiles/zsh/conf.d"
use = ["{aliases,asdf,peco,google-cloud-sdk,navi,zoxide}.zsh"]
apply = ["defer"]
